### ISSUE TITLE
Spaceman Feedback

### ISSUE THREAD

**Issue by natepill** [mdrame/SpaceMan#1]
**Reason why not passing:**
Need to hide secret word from the user

**Additional Feedback**
Fantastic Readme!
Good use of inbuilt libraries
Like the idea of encouragement when you get something right.
Good comments

Fantastic use of docstrings following PEP8 convention
Great variable and function naming
When I enter alphabet characters that are not in the secret word, the program tells me I cannot enter numbers.
Must implement some form of a counter for lives/tries to limit the number of guesses

**Comment by mdrame** [comment]
thanks for the feedback working on it ✅
